version: "3"
services:
  wg-access-server:
    # to build the docker image from the source
    # build:
    #   dockerfile: Dockerfile
    #   context: .
    image: place1/wg-access-server
    restart: always
    container_name: wg-access-server
    cap_add:
      - NET_ADMIN
    volumes:
      - "wg-access-server-data:/data"
      - "./config.yaml:/config.yaml"
    ports:
      - "9009:8000/tcp"
      - "51820:51820/udp"
    devices:
      - "/dev/net/tun:/dev/net/tun"

  wg-monitor:
    build: "./monitor"
    restart: always
    depends_on:
      - wg-access-server
    container_name: wg-monitor
    volumes:
      - "wg-access-server-data:/data"
    environment:
      - "WG_MONITOR_DB=/data/db.sqlite3"


# shared volumes with the host
volumes:
  wg-access-server-data:
    driver: local
